### PR TITLE
fix: Prevent input undefined

### PR DESCRIPTION
**Pull request by ppokemon**

### CODE REVIEW

**Comment by ppokemon** [comment]
🙏

**Comment by KODerFunk** [comment]
Hi @ppokemon! 
Can you describe your problem in more detail? 
In what situation source is not defined?

**Comment by ppokemon** [comment]
emmm.

**Comment by ppokemon** [comment]
"parcel-bundler": "^1.12.3",
"postcss-aspect-ratio-mini": "^1.0.1",
"postcss-font-magician": "^2.2.1",
"postcss-modules": "^1.4.1",
"postcss-preset-env": "^6.6.0",Undefined using these plugins

**Comment by ppokemon** [comment]
I didn't figure out exactly what plugin was causing undefined, but this commit can circumvent this problem.

**Comment by KODerFunk** [comment]
@ppokemon `postcss-preset-env` have mass dependencies. Can you list error there?

**Comment by ppokemon** [comment]
[](https://github.com/ppokemon/one-community) The dev branch can reproduce this problem

**Comment by KODerFunk** [comment]
@ppokemon, ok, i detect problem. It is from [`postcss-modules-values`](https://github.com/css-modules/postcss-modules-values/blob/master/src/index.js#L91-L99). It append rules with selector `:export` that can be ignored. Ok! Merge, but new version in npm at the end of week. Pika pika!

**Comment by ppokemon** [comment]
Thanks!!!😆

**Comment by ppokemon** [comment]
new version？？？

**Comment by KODerFunk** [comment]
Oh sorry! My bad! Tomorrow.

**Comment by KODerFunk** [comment]
@ppokemon I coped with the release! v1.1.1
Thanks again!

**Comment by ppokemon** [comment]
@KODerFunk  yeah! I see~ 😀

**Pull request merged**
