### PR TITLE
 add exlclude option to ignore some files

### PR DESCRIPTION
**Pull request by msidolphin**
https://github.com/evrone/postcss-px-to-viewport/issues/11

### CODE REVIEW

**Comment by chernobelenkiy** [comment]
@msidolphin thank you for your PR. We've added some tests recently. Could you do rebase and add some test coverage too?

**Comment by msidolphin** [comment]
@chernobelenkiy of course, I've added test cases.

**Comment by KODerFunk** [comment]
@msidolphin good job! 👍

**Comment by 501981732** [comment]
sixsixsix!

**Pull request merged**
